#!/usr/bin/env node
/* Pulls every logged day out of Supabase and writes it into logs/.

   Two outputs, on purpose:
     logs/workout-export.json  byte-compatible with the app's own "Export
                               everything", so it can be fed straight back
                               into "Restore from a file".
     logs/log.md               the same data as prose, so the repo is
                               readable without running anything.

   The email is NOT stored in this repo — it is read from $WORKOUT_EMAIL or
   from ~/.workout-export.env. This repo is public; an address committed here
   is an address that gets scraped.

   Auth mirrors the app exactly: the password is sha256(email + salt), with the
   salt read out of config.js rather than duplicated, so the two cannot drift. */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

const APP = dirname(dirname(fileURLToPath(import.meta.url)));
const die = (m) => { console.error("export-logs: " + m); process.exit(1); };

/* ---- config, read from the app so it cannot drift ---- */
const cfg = readFileSync(join(APP, "config.js"), "utf8");
const pick = (k) => (cfg.match(new RegExp(k + '\\s*:\\s*"([^"]+)"')) || [])[1];
const URL_ = pick("url"), ANON = pick("anonKey"), SALT = pick("salt");
if (!URL_ || !ANON || !SALT) die("could not read url/anonKey/salt from config.js");

/* ---- the one secret, kept out of the repo ---- */
function email() {
  if (process.env.WORKOUT_EMAIL) return process.env.WORKOUT_EMAIL.trim().toLowerCase();
  const f = join(homedir(), ".workout-export.env");
  if (existsSync(f)) {
    const m = readFileSync(f, "utf8").match(/WORKOUT_EMAIL\s*=\s*(\S+)/);
    if (m) return m[1].trim().toLowerCase();
  }
  die("no email. Put WORKOUT_EMAIL=you@example.com in ~/.workout-export.env (chmod 600).");
}

/* ---- exercise names, parsed from PLAN so a rename here is impossible ---- */
function names() {
  const src = readFileSync(join(APP, "app.js"), "utf8");
  const out = {};
  for (const m of src.matchAll(/\{\s*id:"([a-z0-9]+)",\s*n:"([^"]+)"/g)) out[m[1]] = m[2];
  for (const m of src.matchAll(/([a-z0-9]+):\s*\{\s*id:"\1",\s*n:"([^"]+)"/g)) out[m[1]] = m[2];
  return out;
}

const api = async (path, opts = {}) => {
  const r = await fetch(URL_ + path, {
    ...opts,
    headers: { apikey: ANON, "Content-Type": "application/json", ...(opts.headers || {}) },
  });
  const body = await r.text();
  let j = null; try { j = JSON.parse(body); } catch {}
  if (!r.ok) die(`${path} -> HTTP ${r.status} ${(j && (j.error_description || j.msg || j.message)) || body.slice(0, 200)}`);
  return j;
};

const em = email();
const password = createHash("sha256").update(em + SALT).digest("hex");

const auth = await api("/auth/v1/token?grant_type=password", {
  method: "POST", body: JSON.stringify({ email: em, password }),
});
const tok = auth.access_token;
if (!tok) die("signed in but got no access token");

/* Page through rather than trusting one request to return everything. */
const days = {};
let from = 0, got = 0;
for (;;) {
  const page = await api("/rest/v1/days?select=day,payload,updated_at&order=day.asc", {
    headers: { Authorization: "Bearer " + tok, Range: `${from}-${from + 999}` },
  });
  if (!page || !page.length) break;
  for (const row of page) {
    const p = row.payload || {};
    p.ex = p.ex || {};
    if (p.updatedAt == null) p.updatedAt = Date.parse(row.updated_at) || 0;
    days[row.day] = p;
  }
  got += page.length;
  if (page.length < 1000) break;
  from += 1000;
}

const keys = Object.keys(days).sort();
if (!keys.length) die("signed in as " + em + " but the account has no rows. Wrong address?");

/* ---- 1. the machine-readable copy, identical in shape to the app's export ---- */
const LOGS = join(APP, "logs");
mkdirSync(LOGS, { recursive: true });
const build = (readFileSync(join(APP, "app.js"), "utf8").match(/var BUILD = (\d+)/) || [])[1];
writeFileSync(join(LOGS, "workout-export.json"),
  JSON.stringify({ v: 2, build: build ? +build : null, exported: new Date().toISOString(), days }, null, 1));

/* ---- 2. the human-readable copy ---- */
const N = names();
const DOW = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MON = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const pretty = (s) => { const [y, m, d] = s.split("-").map(Number);
  const dt = new Date(y, m - 1, d); return `${DOW[dt.getDay()]} ${d} ${MON[m - 1]} ${y}`; };

const lines = ["# Training log", "",
  `Exported ${new Date().toISOString().slice(0, 16).replace("T", " ")} · ${keys.length} days · generated by \`tools/export-logs.mjs\`, do not edit by hand.`,
  "", "---", ""];

let sessions = 0, sets = 0;
for (const d of keys.slice().reverse()) {
  const rec = days[d], ex = rec.ex || {};
  const ids = Object.keys(ex).filter((id) => (ex[id].r || []).some((v) => v != null && v !== ""));
  if (!ids.length && !rec.note) continue;
  if (ids.length) sessions++;
  lines.push(`## ${pretty(d)}`, "");
  for (const id of ids) {
    const e = ex[id];
    const reps = (e.r || []).filter((v) => v != null && v !== "");
    sets += reps.length;
    const marked = reps.map((v, i) => v + ((e.q || [])[i] === 0 ? "!" : "")).join(" ");
    const w = e.w != null ? `${e.w}kg` : "bodyweight";
    lines.push(`- **${N[id] || id}** ${w} — ${marked}`);
  }
  if (rec.note) lines.push("", `> ${String(rec.note).replace(/\n/g, "\n> ")}`);
  lines.push("");
}
lines.push("---", "", `${sessions} sessions · ${sets} sets logged · \`!\` marks a set taken to failure early.`, "");
writeFileSync(join(LOGS, "log.md"), lines.join("\n"));

console.log(`export-logs: ${keys.length} days, ${sessions} sessions, ${sets} sets -> logs/`);
